CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  status TEXT NOT NULL CHECK(status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  input_file TEXT NOT NULL,
  output_file TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);